easy_admin:
    site_name: '<img src="/images/head_banner_pro.png" />'

    entities:
        Student:
            class: App\Entity\Student
            label: Elèves
        Dossier:
            class: App\Entity\Review
        ProfPrincipal:
            label: Prof. principal
            class: App\Entity\Referent
            form:
                fields:
                    - {type: 'tab', label: 'Informations'}
                    - firstname
                    - lastname
                    - gender
                    - {type: 'tab', label: 'Elèves'}
                    - {property: students}
        Lycée:
            class: App\Entity\School
        CIRFA:
            class: App\Entity\Cirfa
        SRM:
            class: App\Entity\Srm
        Spécialisation:
            class: App\Entity\Specialisation
        TP:
            class: App\Entity\Tp
        Compétence:
            class: App\Entity\Competence
        Utilisateur:
            class: App\Entity\User
