easy_admin:
    entities:
        Eleve:
            class: App\Entity\Student
            label: 'Elèves'
            list:
                title: 'Liste des élèves'
                fields:
                    - {property: gender, label: 'Civilité'}
                    - {property: lastname, label: 'Nom'}
                    - {property: firstname, label: 'Prénom'}
                    - {property: birthdate, label: 'Date de naissance', type: 'date'}
                    - {property: birthplace, label: 'Lieu de naissance'}
                    - {property: city, label: 'Ville'}
                    - {property: school, label: 'Lycée'}
                    - {property: cirfa, label: 'CIRFA'}
                    - {property: srm, label: 'SRM'}
                    - {property: bordee, label: 'Bordée'}
            show:
                title: 'Eleve'
                fields:
                    - {property: gender, label: 'Civilité'}
                    - {property: lastname, label: 'Nom'}
                    - {property: firstname, label: 'Prénom'}
                    - {property: birthdate, label: 'Date de naissance', type: 'date'}
                    - {property: birthplace, label: 'Lieu de naissance'}
                    - {property: city, label: 'Ville'}
                    - {property: school, label: 'Lycée'}
                    - {property: cirfa, label: 'CIRFA'}
                    - {property: srm, label: 'SRM'}
                    - {property: bordee, label: 'Bordée'}
            form:
                title: 'Eleve'
                fields:
                    - {property: gender, label: 'Civilité'}
                    - {property: lastname, label: 'Nom'}
                    - {property: firstname, label: 'Prénom'}
                    - {property: birthdate, type: 'birthday', label: 'Date de naissance', type_options: { format: 'dd-MM-yyyy'}}
                    - {property: birthplace, label: 'Lieu de naissance'}
                    - {property: city, label: 'Ville'}
                    - {property: school, label: 'Lycée'}
                    - {property: cirfa, label: 'CIRFA'}
                    - {property: srm, label: 'SRM'}
                    - {property: bordee, label: 'Bordée'}
            edit:
                title: 'Modifier un elève'
            new:
                title: 'Créer un elève'
        Dossier:
            class: App\Entity\Review
        ProfPrincipal:
            label: Prof. principal
            class: App\Entity\Referent
            list:
                title: 'Liste des Prof. principaux'
                fields:
                    - {property: gender, label: 'Civilité'}
                    - {property: lastname, label: 'Nom'}
                    - {property: firstname, label: 'Prénom'}
            show:
                title: 'Prof. principal'
                fields:
                    - {property: gender, label: 'Civilité'}
                    - {property: lastname, label: 'Nom'}
                    - {property: firstname, label: 'Prénom'}
                    - {property: students, label: 'Elèves'}
            form:
                title: 'Prof. principal'
                fields:
                    - {type: 'tab', label: 'Informations'}
                    - {property: gender, label: 'Civilité'}
                    - {property: lastname, label: 'Nom'}
                    - {property: firstname, label: 'Prénom'}
                    - {type: 'tab', label: 'Elèves'}
                    - {property: students, label: 'Elèves'}
            edit:
                title: 'Modifier un prof. principal'
            new:
                title: 'Modifier un prof. principal'
        Lycee:
            label: 'Lycée'
            class: App\Entity\School
            list:
                title: 'Liste des lycées'
                fields:
                    - {property: name, label: 'Nom'}
                    - {property: academy, label: 'Académie'}
                    - {property: number, label: 'Téléphone'}
                    - {property: email, label: 'Email'}
            show:
                title: 'Lycée'
                fields:
                    - {property: name, label: 'Nom'}
                    - {property: academy, label: 'Académie'}
                    - {property: number, label: 'Téléphone'}
                    - {property: email, label: 'Email'}
                    - {property: students, label: 'Elèves'}
            form:
                title: 'Lycée'
                fields:
                    - {type: 'tab', label: 'Informations'}
                    - {property: name, label: 'Nom'}
                    - {property: academy, label: 'Académie'}
                    - {property: number, label: 'Téléphone'}
                    - {property: email, label: 'Email'}
                    - {type: 'tab', label: 'Elèves'}
                    - {property: students, label: 'Elèves'}
            edit:
                title: 'Modifier un lycée'
            new:
                title: 'Créer un lycée'
        CIRFA:
            class: App\Entity\Cirfa
            label: 'CIRFA'
            list:
                title: 'Liste des CIRFA'
                fields:
                    - {property: city, label: 'Ville'}
                    - {property: number, label: 'Téléphone'}
                    - {property: email, label: 'Email'}
            show:
                title: 'CIRFA'
                fields:
                    - {property: city, label: 'Ville'}
                    - {property: number, label: 'Téléphone'}
                    - {property: email, label: 'Email'}
                    - {property: students, label: 'Elèves'}
            form:
                title: 'CIRFA'
                fields:
                    - {type: 'tab', label: 'Informations'}
                    - {property: city, label: 'Ville'}
                    - {property: number, label: 'Téléphone'}
                    - {property: email, label: 'Email'}
                    - {type: 'tab', label: 'Elèves'}
                    - {property: students, label: 'Elèves'}
            edit:
                title: 'Modifier un CIRFA'
            new:
                title: 'Créer un CIRFA'
        SRM:
            class: App\Entity\Srm
            label: 'SRM'
            list:
                title: 'Liste des SRM'
                fields:
                    - {property: name, label: 'Nom'}
                    - {property: email, label: 'Email'}
            show:
                title: 'SRM'
                fields:
                    - {property: name, label: 'Nom'}
                    - {property: email, label: 'Email'}
                    - {property: students, label: 'Elèves'}
            form:
                title: 'SRM'
                fields:
                    - {type: 'tab', label: 'Informations'}
                    - {property: name, label: 'Nom'}
                    - {property: email, label: 'Email'}
                    - {type: 'tab', label: 'Elèves'}
                    - {property: students, label: 'Elèves'}
            edit:
                title: 'Modifier un SRM'
            new:
                title: 'Créer un SRM'
        Specialisation:
            class: App\Entity\Specialisation
            label: 'Spécialisation'
            list:
                title: 'Liste des spécialisations'
                fields:
                    - {property: name, label: 'Intitulé'}
            show:
                title: 'Spécialisation'
                fields:
                    - {property: name, label: 'Intitulé'}
                    - {property: competence, label: 'Compétences'}
                    - {property: tps, label: 'Travaux pratiques'}
                    - {property: students, label: 'Eleves'}
            form:
                title: 'Spécialisation'
                fields:
                    - {type: 'tab', label: 'Informations'}
                    - {property: name, label: 'Intitulé'}
                    - {type: 'tab', label: 'Compétences'}
                    - {property: competence, label: 'Compétences'}
                    - {type: 'tab', label: 'Travaux pratiques'}
                    - {property: tps, label: 'Travaux pratiques'}
                    - {type: 'tab', label: 'Eleves'}
                    - {property: students, label: 'Eleves'}
            edit:
                title: 'Modifier une spécialisation'
            new:
                title: 'Créer une spécialisation'
        TP:
            class: App\Entity\Tp
            label: 'TP'
            list:
                title: 'Liste des TPs'
                fields:
                    - {property: name, label: 'Intitulé'}
                    - {property: specialisation, label: 'Spécialisation'}
            show:
                title: 'TPs'
                fields:
                    - {property: name, label: 'Intitulé'}
                    - {property: specialisation, label: 'Spécialisation'}
                    - {property: competence, label: 'Compétences'}
            form:
                title: 'TP'
                fields:
                    - {type: 'tab', label: 'Informations'}
                    - {property: name, label: 'Intitulé'}
                    - {property: specialisation, label: 'Spécialisation'}
                    - {type: 'tab', label: 'Compétences'}
                    - {property: competence, label: 'Compétences'}
            edit:
                title: 'Modifier un TP'
            new:
                title: 'Créer un TP'
        Competence:
            class: App\Entity\Competence
            label: 'Compétences'
            list:
                title: 'Liste des compétences'
                fields:
                    - {property: reference, label: 'Référence'}
                    - {property: name, label: 'Intitulé'}
                    - {property: specialisation, label: 'Spécialisation'}
            show:
                title: 'Compétences'
                fields:
                    - {property: reference, label: 'Référence'}
                    - {property: name, label: 'Intitulé'}
                    - {property: specialisation, label: 'Spécialisation'}
                    - {property: tps, label: 'Travaux pratiques'}
            form:
                title: 'Compétences'
                fields:
                    - {type: 'tab', label: 'Informations'}
                    - {property: reference, label: 'Référence'}
                    - {property: name, label: 'Intitulé'}
                    - {property: specialisation, label: 'Spécialisation'}
                    - {type: 'tab', label: 'Travaux pratiques'}
                    - {property: tps, label: 'Travaux pratiques'}
            edit:
                title: 'Modifier une compétences'
            new:
                title: 'Créer une compétences'
        Utilisateur:
            class: App\Entity\User
            label: 'Utilisateurs'
            icon: user
            list:
                title: 'Liste des tilisateurs'
                fields:
                    - {property: username, label: 'Username'}
                    - {property: firstname, lasbel: 'Prénom'}
                    - {property: lastname, label: 'Nom'}
                    - {property: email, label: 'Email'}
                    - {property: number, label: 'Téléphone'}
                    - {property: grade, label: 'Grade'}
            show:
                title: 'Utilisateurs'
                fields:
                    - {property: username, label: 'Username'}
                    - {property: firstname, lasbel: 'Prénom'}
                    - {property: lastname, label: 'Nom'}
                    - {property: email, label: 'Email'}
                    - {property: number, label: 'Téléphone'}
                    - {property: grade, label: 'Grade'}
            form:
                title: 'Utilisateur'
                fields:
                    - {property: username, label: 'Username'}
                    - {property: firstname, lasbel: 'Prénom'}
                    - {property: lastname, label: 'Nom'}
                    - {property: email, label: 'Email'}
                    - {property: number, label: 'Téléphone'}
                    - {property: grade, label: 'Grade'}
            edit:
                title: 'Modifier un utilisateur'
            new:
                title: 'Créer un utilisateur'
    formats:
        date: 'd/m/Y'
    design:
        brand_color: '#000080'
        menu:
            - {entity: Eleve, icon: graduation-cap}
            - {entity: Dossier, icon: folder-open}
            - {entity: ProfPrincipal, icon: user-md}
            - {entity: Lycee, icon: university}
            - {entity: CIRFA, icon: home}
            - {entity: SRM, icon: building-o}
            - {entity: Competence, icon: puzzle-piece}
            - {entity: TP, icon: briefcase}
            - {entity: Specialisation, icon: book}
            - {entity: Utilisateur, icon: users}
    site_name: '<img src="/images/head_banner_pro.png" />'
    list:
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
            - { name: 'new', icon: 'plus-circle', label: Nouveau }